### PR TITLE
Include cindys destinations

### PR DESCRIPTION
**Pull request by cindyjetskis**
We're gonna travel the world together! ✈️ 🚋 ⛵️

### CODE REVIEW

**Comment by atab68** [comment]
Me too 👍

**Comment by kamalmories** [comment]
We're gonna travel

**Comment by hafsahRizg** [comment]
Hi

**Comment by seanjigo** [comment]
hmmmm

**Comment by Engcomm** [comment]
Hello

**Comment by kamalmories** [comment]
Sent from Yahoo Mail on Android 
 
  On Tue, Jun 26, 2018 at 11:28 PM, Engcomm<notifications@github.com> wrote:   
Hello

**Comment by khaledaazzam** [comment]
i m in

**Comment by muhiazher** [comment]
I have plan to visit Paris next week, you can coming with us :)

**Comment by alisicama** [comment]
Let's go together

**Pull request closed without merging**
